### ISSUE TITLE
The plugin breaks Obsidian 1.5.3 (might be a plugin conflict issue)

### ISSUE THREAD

**Issue by lunule** [chhoumann/MetaEdit#104]
Hi @chhoumann,

Thanks for your swift reply in my previous submission - unfortunately, I can't show screenshots - I already lost 2 hours with resetting and reconfiguring my Obsidian app after the accident.

All the info I have is some env/plugin info - the issue occurred in a vault with the following plugins installed:
- Commander
- Typewriter
- Templater
- Tasks
- Workspaces Plus
- Fullscreen Plugin
... among others.

The "breaking" means that all key bindings, all tooltips, and all UI buttons stopped working - basically, the app _really_ completely broke, meaning it became unusable.

The only way to fix the issue was uninstalling the MetaEdit plugin.

Additionally: I tested what happens if I reinstall the plugin - the issue reoccurred, and I had to reset and reconfigure everything again.

---

If it's possible, please keep this one open - I'm happy to edit the title to something you recommend over the one I used here, but I think it's important for others to see that the plugin can cause serious issues in specific circumstances, even if it works perfectly with a different plugin set.

Thanks 👍

**Comment by chhoumann** [comment]
Hi @lunule,

Thank you for the description!
It sounds like most of the `.obsidian` folder was somehow either erased or corrupted.
I'm sad to hear that happened - it's an enormous pain to deal with! Hopefully you had some back up of some kind to recover from.

Could there have been some sync tool you've been using? Say, Google Drive, iCloud, or the likes?
Did you reinstall the plugin with a fresh vault, or in your existing vault?

Conflicts between plugins / sync services are pretty hard to debug. I'm not certain that is exactly what caused this, but it sounds most probable here. MetaEdit should only consider itself with the `.obsidian/plugins/metaedit/` folder, outside of editing notes in your vault.

I tried installing MetaEdit in a fresh vault, plus I've been using it in my own vault, but haven't encountered any issues. I'm not sure MetaEdit is at fault here - individually or in a plugin conflict, but would be interested in hearing if anyone can recreate this issue.

**Comment by lunule** [comment]
👍 Thanks, @chhoumann.

> Could there have been some sync tool you've been using? Say, Google Drive, iCloud, or the likes?

Nope, I don't use sync tools.

Anyhoo, I'm closing this issue now, as it seems to be unreproducible in other environments. 
I don't have time to re-test again, but I'm planning to take another look at it in a few weeks from now - if I'll find something that might help the debugging, I'll open a new issue with reference to this one.

**Comment by chhoumann** [comment]
Thank you, please let me know @lunule!
