### ISSUE TITLE
Please make a tutorials for kanban helper #documentation

### ISSUE THREAD

**Issue by shaggyfeng** [chhoumann/MetaEdit#22]
It will be wonderful if you would like to make a tutorial for kanban helper. I tried for a few days to get it to work, but I am too noob. A few pictures or a GIF or a video can help a lot. Thank you for all your works again.

**Comment by chhoumann** [comment]
Hey! Apologies for the late response. Here's a short video of how it works. I'll add it to the documentation.


https://user-images.githubusercontent.com/29108628/121333246-ebf48200-c918-11eb-889b-23b9a80299b2.mp4

**Comment by shaggyfeng** [comment]
Thank you very much! This is perfect.

**Comment by shaggyfeng** [comment]
Oh, wait. It does not auto change the metadata. Maybe I should not use weird characters for properties. Anyway, thanks for the help.

**Comment by chhoumann** [comment]
> Oh, wait. It does not auto change the metadata. Maybe I should not use weird characters for properties. Anyway, thanks for the help.

I thought any characters worked! Sorry. Which characters are you trying to use? I'll see if I can fix it.

**Comment by chhoumann** [comment]
I think this might be related to #23 - could you see if it's fixed with the latest update?

**Comment by shaggyfeng** [comment]
I should have closed this a while ago. Everything looks fine.
