### ISSUE TITLE
MetaEdit will not change metadata of kanban note.

### ISSUE THREAD

**Issue by 0xDezzy** [chhoumann/MetaEdit#23]
When the note that is created is stored in a folder, changing the column that the card is in will not update the metadata. From my testing, it needs to be in the root for metaedit to update the kanban card's metadata.

**Comment by chhoumann** [comment]
Thanks for your report! I'll fix it ASAP :)

**Comment by chhoumann** [comment]
Should be fixed now :)

**Comment by chhoumann** [comment]
Should be fixed now :)

**Comment by 0xDezzy** [comment]
Thanks!
