### ISSUE TITLE
Expose create property in API

### ISSUE THREAD

**Issue by bikingbadger** [chhoumann/MetaEdit#27]
Really interesting tool. I'm currently trying to add a property to my files where they don't exist and update where it does. The update works great but unfortunately I can't find anything for creating a property. Is there any way of exposing this functionality in the API?

**Comment by chhoumann** [comment]
Hey. I've exposed `createYamlProperty(propertyName: string, propertyValue: string, file: TFile | string)`. Hope this helps!

I am currently working on improvements to both the API and the backend stuff, so more is coming.

**Comment by bikingbadger** [comment]
Brilliant, I'll give it a try thanks
