### ISSUE TITLE
Edit existing values with Edit Meta right click menu

### ISSUE THREAD

**Issue by 06000208** [chhoumann/MetaEdit#28]
When using the Edit Meta right click menu, it seems to only be able to overwrite the field with a new value, "Enter a new value for <field", rather than editing.

When editing a field with the menu, could the input's content be populated with the current value, instead of putting it in a placeholder attribute? This would allow for quick editing instead of having to retype the whole value to use it to make edits, and wouldn't hinder the current purpose.

**Comment by chhoumann** [comment]
Hey! Thank you for your request. I've implemented this feature in 1.6.16.

Please do tell me if it's not as you desired. If it's all good, you can go ahead and close this issue. :)

**Comment by 06000208** [comment]
Thanks 👍
