### ISSUE TITLE
Add #obsidian-plugin topic to this repository #48

### ISSUE THREAD

**Issue by andyconlin** [chhoumann/MetaEdit#5]
Hey @chhoumann, the developer of the [Buttons](https://github.com/shabegom/buttons) plugin [pointed me](https://github.com/shabegom/buttons/issues/39#issuecomment-843136130) to MetaEdit when I was looking for a plugin for something to do some quick frontmatter CRUD actions. I haven't yet tried your plugin, but it looks like something I may make use of.

I wanted to suggest that you [add the topic](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) of ```obsidian-plugin``` to this repository to help others find it. I've been making use of [#obsidian-plugin](https://github.com/topics/obsidian-plugin) to see what's available, and I imagine others are, as well.

**Comment by chhoumann** [comment]
Good idea! Done 👍
