### ISSUE TITLE
Excalidraw file modified by MetaEdit while drawing causes loss of data

### ISSUE THREAD

**Issue by zsviczian** [chhoumann/MetaEdit#50]
Please see this issue raised by @zhl111 for Excalidraw [#296](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/296).

@zhl111 singled out MetaEdit as the root cause of the data loss by way of elimination... i.e. turning off plugins one-by-one until only MetaEdit was left.

I haven't done detailed testing, however, my assumptions are the following:
- It seems that while editing an Excalidraw drawing somehow MetaEdit is triggered. This could be linked to Excalidraw autosave.
- When MetaEdit is triggered, it probably modifies the excalidraw.md file, which in turn is interpreted by Excalidraw as a trigger to reload the drawing. Note, that I monitor background file changes to allow use-cases such as editing the same file side by side in markdown mode and in drawing mode, as well as to handle file sync events, such as when using Obsidian sync.

I recommend adding the following logic to [onFileModify()](https://github.com/chhoumann/MetaEdit/blob/95e9fc662d170da52a8c83119e174e33dc58276b/src/automators/onFileModifyAutomatorManager.ts#L28) (and potentially other relevant functions) avoid this issue:
`if (app.workspace.activeLeaf.view.getViewType()==="excalidraw") return;`

**Comment by chhoumann** [comment]
Hey @zsviczian, thank you very much for reporting this!

This `onFileModify` function helps facilitate a queue, and by rejecting the active pane rather than the file that the event regards, possible issues can occur.

I've made a fix, but it depends on metadata in Excalidraw files. Does Excalidraw files always have a metadata key with `Excalidraw` in the name?

```js
const metadata = await this.app.metadataCache.getFileCache(outfile);
const keys = Object.keys(metadata?.frontmatter);
if (keys && keys.some(key => key.toLowerCase().contains("excalidraw"))) {
    return;
}
```

**Comment by zsviczian** [comment]
yes

**Comment by m-paul** [comment]
I'm encountering an exception attributed to this code change [here](https://github.com/chhoumann/MetaEdit/blob/a835c7932990b8a5ee1350e56312389122109c01/src/automators/onFileModifyAutomatorManager.ts#L62). Looks like when OnFileModifyAutomatorManager.onFileModify is called, the object returned from `this.app.metadataCache.getFileCache(outfile)` doesn't always have a frontmatter property, which results in uncaught in promise excpetion `TypeError: Cannot convert undefined or null to object` when the next line is called.

**Comment by zsviczian** [comment]
It seems metachache is updated asynchronously.

This is my isExcalidraw() function. I do check if frontmatter exists...

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/857f41ad0710d4708e815eeecb3435f425cf71ce/src/main.ts#L1791-L1797

on a related note, I have a separate event handler to monitor metachache changes and to maintain a list of Excalidraw drawings:

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/857f41ad0710d4708e815eeecb3435f425cf71ce/src/main.ts#L1493-L1529
