### ISSUE TITLE
Tags for statuses?

### ISSUE THREAD

**Issue by weeyizhi** [chhoumann/MetaEdit#6]
Not sure if you accept feature requests, but here we go...

Any plans to add support for changing tags for statuses instead of a YAML/dataview key? I prefer using tags for statuses to ease searching/creating dataviews.
for example, my files' statuses are indicated using the tag `#my-status/new`, `#my-status/to-do`, `#my-status/done`, etc

**Comment by chhoumann** [comment]
Added :)
