### ISSUE TITLE
Update a single value in a property with multiple values

### ISSUE THREAD

**Issue by Excali6ur** [chhoumann/MetaEdit#68]
I'm trying to update the second value of a propery. (2nd being the status)
```
tags:
  - 📥/📘
  - 🗃️/🔷/🔴
```
I'm reading everywhere from last year, that such functionality could be added, but I can't find if it actually has been done. 
Is there method, or at least a workaround?

**Comment by AB1908** [comment]
This works, there's a setting like this:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/14124383/164547084-5b0ace86-11be-4231-b8ee-811ca2c637a8.png">

**Comment by Excali6ur** [comment]
Welp.. already split them up into different properties. will be monitoring status with dataview(s) so tags are not that neccessary tbh. But it's good to know (for the future). Thank you.
