### ISSUE TITLE
How to use Auto Properties

### ISSUE THREAD

**Issue by taylorjason** [chhoumann/MetaEdit#71]
How do we create multiple choices for the values of an "Auto Property" as shown in the helper videos for the "Status" property? In the video the Status property has pre-selected values such as "Completed". Can't figure out how to get more than one value as an option

I've tried commas, semi-colons, pipes, spaces, tabs.

**Comment by kalmir** [comment]
I guess I know how to create multiple choices: not by a delimiter but by clicking on the plus icon to the right of Values section.

However, even if I do that - or add just one value - I am still unable to make it work with Dataview fields. MetaEdit doesnt offer values from the settings. Not sure why.

**Comment by taylorjason** [comment]
Ah! I see it now. With my theme the Plus is almost not visible. Maybe it should be a different color?
<img width="284" alt="image" src="https://user-images.githubusercontent.com/8422821/169698815-107895a3-f4c9-4662-a37d-e3bf38b8073e.png">
