### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by tgrosinger** [chhoumann/MetaEdit#9]
@chhoumann, your plugin has some awesome functions for interacting with the frontmatter that I would like to leverage in one of my plugins. Would you be willing to add a license to your repo so I can do so?

Thank you!

**Comment by tgrosinger** [comment]
In Github if you click "Add File" from the repo main page, and name it "LICENSE" Github with automatically suggest some options and make it very easy.

**Comment by chhoumann** [comment]
Sure thing. Added a license :)
